# Generated by Django 6.0.5 on 2026-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timbrado', models.CharField(max_length=20, verbose_name='N° Timbrado')),
                ('timbrado_valid_from', models.DateField(verbose_name='Vigencia desde')),
                ('timbrado_valid_until', models.DateField(verbose_name='Vigencia hasta')),
                ('invoice_point', models.CharField(default='001', max_length=3, verbose_name='Punto de expedición')),
                ('invoice_establishment', models.CharField(default='001', max_length=3, verbose_name='N° establecimiento')),
                ('invoice_sequence', models.PositiveIntegerField(default=1, verbose_name='Secuencia actual')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfil de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='N° Factura')),
                ('timbrado', models.CharField(max_length=20, verbose_name='N° Timbrado')),
                ('timbrado_valid_until', models.DateField(verbose_name='Vigencia timbrado')),
                ('status', models.CharField(choices=[('generated', 'Generada'), ('sent', 'Enviada'), ('cancelled', 'Cancelada (Anulada)')], default='generated', max_length=20)),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal Exento')),
                ('subtotal_iva5', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal gravado 5%')),
                ('subtotal_iva10', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal gravado 10%')),
                ('iva5_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA 5%')),
                ('iva10_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA 10%')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
